import model

Slots = model.Slots()

Slots.abertura_minima_automatica('Brasília', 'vaccines', 60, 15, 0, 2, 50)
Slots.abertura_minima_automatica('Brasília', 'vaccines', 60, 6, 3, 4, 50)
Slots.abertura_minima_automatica('Brasília', 'vaccines', 60, 1, 5, 6, 50)
Slots.abertura_sob_demanda_automatica('Brasília', 'vaccines', 15, 0.30, 50, 1)
Slots.abertura_sob_demanda_automatica('Brasília', 'vaccines', 10, 0.60, 50, 1)
Slots.abertura_sob_demanda_automatica('Brasília', 'vaccines', 7, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Brasília', 'vaccines', 6, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Brasília', 'vaccines', 5, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Brasília', 'vaccines', 4, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Brasília', 'vaccines', 3, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Brasília', 'vaccines', 2, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Brasília', 'vaccines', 1, 0, 50, 0)

Slots.abertura_minima_automatica('Brasília', 'laboratories', 60, 15, 0, 2, 50)
Slots.abertura_minima_automatica('Brasília', 'laboratories', 60, 6, 3, 4, 50)
Slots.abertura_minima_automatica('Brasília', 'laboratories', 60, 1, 5, 6, 50)
Slots.abertura_sob_demanda_automatica('Brasília', 'laboratories', 15, 0.30, 50, 1)
Slots.abertura_sob_demanda_automatica('Brasília', 'laboratories', 10, 0.60, 50, 1)
Slots.abertura_sob_demanda_automatica('Brasília', 'laboratories', 7, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Brasília', 'laboratories', 6, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Brasília', 'laboratories', 5, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Brasília', 'laboratories', 4, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Brasília', 'laboratories', 3, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Brasília', 'laboratories', 2, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Brasília', 'laboratories', 1, 0, 50, 0)

Slots.abertura_minima_automatica('Curitiba', 'vaccines', 60, 15, 0, 2, 50)
Slots.abertura_minima_automatica('Curitiba', 'vaccines', 60, 6, 3, 4, 50)
Slots.abertura_minima_automatica('Curitiba', 'vaccines', 60, 1, 5, 6, 50)
Slots.abertura_sob_demanda_automatica('Curitiba', 'vaccines', 15, 0.30, 50, 1)
Slots.abertura_sob_demanda_automatica('Curitiba', 'vaccines', 10, 0.60, 50, 1)
Slots.abertura_sob_demanda_automatica('Curitiba', 'vaccines', 7, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Curitiba', 'vaccines', 6, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Curitiba', 'vaccines', 5, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Curitiba', 'vaccines', 4, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Curitiba', 'vaccines', 3, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Curitiba', 'vaccines', 2, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Curitiba', 'vaccines', 1, 0, 50, 0)

Slots.abertura_minima_automatica('Curitiba', 'laboratories', 60, 15, 0, 2, 50)
Slots.abertura_minima_automatica('Curitiba', 'laboratories', 60, 6, 3, 4, 50)
Slots.abertura_minima_automatica('Curitiba', 'laboratories', 60, 1, 5, 6, 50)
Slots.abertura_sob_demanda_automatica('Curitiba', 'laboratories', 15, 0.30, 50, 1)
Slots.abertura_sob_demanda_automatica('Curitiba', 'laboratories', 10, 0.60, 50, 1)
Slots.abertura_sob_demanda_automatica('Curitiba', 'laboratories', 7, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Curitiba', 'laboratories', 6, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Curitiba', 'laboratories', 5, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Curitiba', 'laboratories', 4, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Curitiba', 'laboratories', 3, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Curitiba', 'laboratories', 2, 0, 50, 0)
Slots.abertura_sob_demanda_automatica('Curitiba', 'laboratories', 1, 0, 50, 0)

Slots.abertura_minima_automatica('Recife', 'vaccines', 60, 15, 0, 2, 40)
Slots.abertura_minima_automatica('Recife', 'vaccines', 60, 6, 3, 4, 40)
Slots.abertura_minima_automatica('Recife', 'vaccines', 60, 1, 5, 6, 40)
Slots.abertura_sob_demanda_automatica('Recife', 'vaccines', 15, 0.30, 40, 1)
Slots.abertura_sob_demanda_automatica('Recife', 'vaccines', 10, 0.60, 40, 1)
Slots.abertura_sob_demanda_automatica('Recife', 'vaccines', 7, 0, 40, 0)
Slots.abertura_sob_demanda_automatica('Recife', 'vaccines', 6, 0, 40, 0)
Slots.abertura_sob_demanda_automatica('Recife', 'vaccines', 5, 0, 40, 0)
Slots.abertura_sob_demanda_automatica('Recife', 'vaccines', 4, 0, 40, 0)
Slots.abertura_sob_demanda_automatica('Recife', 'vaccines', 3, 0, 40, 0)
Slots.abertura_sob_demanda_automatica('Recife', 'vaccines', 2, 0, 40, 0)
Slots.abertura_sob_demanda_automatica('Recife', 'vaccines', 1, 0, 40, 0)

Slots.abertura_minima_automatica('Recife', 'laboratories', 60, 15, 0, 2, 40)
Slots.abertura_minima_automatica('Recife', 'laboratories', 60, 6, 3, 4, 40)
Slots.abertura_minima_automatica('Recife', 'laboratories', 60, 1, 5, 6, 40)
Slots.abertura_sob_demanda_automatica('Recife', 'laboratories', 15, 0.30, 40, 1)
Slots.abertura_sob_demanda_automatica('Recife', 'laboratories', 10, 0.60, 40, 1)
Slots.abertura_sob_demanda_automatica('Recife', 'laboratories', 7, 0, 40, 0)
Slots.abertura_sob_demanda_automatica('Recife', 'laboratories', 6, 0, 40, 0)
Slots.abertura_sob_demanda_automatica('Recife', 'laboratories', 5, 0, 40, 0)
Slots.abertura_sob_demanda_automatica('Recife', 'laboratories', 4, 0, 40, 0)
Slots.abertura_sob_demanda_automatica('Recife', 'laboratories', 3, 0, 40, 0)
Slots.abertura_sob_demanda_automatica('Recife', 'laboratories', 2, 0, 40, 0)
Slots.abertura_sob_demanda_automatica('Recife', 'laboratories', 1, 0, 40, 0)