import controller

# Vitória vaccines automático do d+30 ao d+60
controller.aberturaautomatica('Vitória', 'vaccines', 60, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 59, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 58, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 57, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 56, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 55, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 54, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 53, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 52, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 51, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 50, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 49, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 48, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 47, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 46, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 45, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 44, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 43, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 42, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 41, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 40, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 39, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 38, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 37, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 36, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 35, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 34, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 33, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 32, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 31, 5, 6, 60)
controller.aberturaautomatica('Vitória', 'vaccines', 30, 5, 6, 60)

# Vitória laboratories automático do d+30 ao d+60
controller.aberturaautomatica('Vitória', 'laboratories', 60, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 59, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 58, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 57, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 56, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 55, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 54, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 53, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 52, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 51, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 50, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 49, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 48, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 47, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 46, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 45, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 44, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 43, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 42, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 41, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 40, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 39, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 38, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 37, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 36, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 35, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 34, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 33, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 32, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 31, 3, 6, 60)
controller.aberturaautomatica('Vitória', 'laboratories', 30, 3, 6, 60)

# Brasília vaccines automático do d+30 ao d+60
controller.aberturaautomatica('Brasília', 'vaccines', 60, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 59, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 58, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 57, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 56, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 55, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 54, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 53, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 52, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 51, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 50, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 49, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 48, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 47, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 46, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 45, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 44, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 43, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 42, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 41, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 40, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 39, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 38, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 37, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 36, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 35, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 34, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 33, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 32, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 31, 5, 6, 40)
controller.aberturaautomatica('Brasília', 'vaccines', 30, 5, 6, 40)



# Brasília laboratories automático do d+30 ao d+60
controller.aberturaautomatica('Brasília', 'laboratories', 60, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 59, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 58, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 57, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 56, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 55, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 54, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 53, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 52, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 51, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 50, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 49, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 48, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 47, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 46, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 45, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 44, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 43, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 42, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 41, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 40, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 39, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 38, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 37, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 36, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 35, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 34, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 33, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 32, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 31, 5, 6, 60)
controller.aberturaautomatica('Brasília', 'laboratories', 30, 5, 6, 60)







# controller.aberturaautomatica('Brasília', 'laboratories', 60, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 59, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 58, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 57, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 56, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 55, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 54, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 53, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 52, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 51, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 50, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 49, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 48, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 47, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 46, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 45, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 44, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 43, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 42, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 41, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 40, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 39, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 38, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 37, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 36, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 35, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 34, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 33, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 32, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 31, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 30, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 29, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 28, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 27, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 26, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 25, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 24, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 23, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 22, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 21, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 20, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 19, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 18, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 17, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 16, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 15, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 14, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 13, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 12, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 11, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 10, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 9, 5, 6, 60)
# controller.aberturaautomatica('Brasília', 'laboratories', 8, 5, 6, 60)