import controller

controller.aberturaautomatica('São Cristóvão', 'vaccines', 60, 15, 0, 2, 40)
controller.aberturaautomatica('São Cristóvão', 'vaccines', 60, 6, 3, 4, 40)
controller.aberturaautomatica('São Cristóvão', 'vaccines', 60, 1, 5, 6, 40)
controller.aberturaautomaticasobdemanda('São Cristóvão', 'vaccines', 15, 0.3, 40, 1)
controller.aberturaautomaticasobdemanda('São Cristóvão', 'vaccines', 10, 0.5, 40, 1)
# controller.aberturaautomaticasobdemanda('São Cristóvão', 'vaccines', 7, 0, 40, 0)

controller.aberturaautomatica('São Cristóvão', 'laboratories', 60, 15, 0, 2, 40)
controller.aberturaautomatica('São Cristóvão', 'laboratories', 60, 6, 3, 4, 30)
controller.aberturaautomatica('São Cristóvão', 'laboratories', 60, 1, 5, 6, 30)
controller.aberturaautomaticasobdemanda('São Cristóvão', 'laboratories', 15, 0.3, 30, 1)
controller.aberturaautomaticasobdemanda('São Cristóvão', 'laboratories', 10, 0.5, 30, 1)
# controller.aberturaautomaticasobdemanda('São Cristóvão', 'laboratories', 7, 0, 30, 0)

controller.aberturaautomatica('Barra', 'vaccines', 60, 15, 0, 2, 40)
controller.aberturaautomatica('Barra', 'vaccines', 60, 6, 3, 4, 40)
controller.aberturaautomatica('Barra', 'vaccines', 60, 1, 5, 6, 40)
controller.aberturaautomaticasobdemanda('Barra', 'vaccines', 15, 0.3, 40, 1)
controller.aberturaautomaticasobdemanda('Barra', 'vaccines', 10, 0.5, 40, 1)
# controller.aberturaautomaticasobdemanda('Barra', 'vaccines', 7, 0, 40, 0)

controller.aberturaautomatica('Barra', 'laboratories', 60, 15, 0, 2, 40)
controller.aberturaautomatica('Barra', 'laboratories', 60, 6, 3, 4, 30)
controller.aberturaautomatica('Barra', 'laboratories', 60, 1, 5, 6, 30)
controller.aberturaautomaticasobdemanda('Barra', 'laboratories', 15, 0.3, 30, 1)
controller.aberturaautomaticasobdemanda('Barra', 'laboratories', 10, 0.5, 30, 1)
# controller.aberturaautomaticasobdemanda('Barra', 'laboratories', 7, 0, 30, 0)

controller.aberturaautomatica('Cabo Frio', 'vaccines', 60, 15, 0, 2, 50)
controller.aberturaautomatica('Cabo Frio', 'vaccines', 60, 6, 3, 4, 50)
controller.aberturaautomatica('Cabo Frio', 'vaccines', 60, 1, 5, 6, 50)
controller.aberturaautomaticasobdemanda('Cabo Frio', 'vaccines', 15, 0.3, 50, 1)
controller.aberturaautomaticasobdemanda('Cabo Frio', 'vaccines', 10, 0.5, 50, 1)
# controller.aberturaautomaticasobdemanda('Cabo Frio', 'vaccines', 7, 0, 50, 0)

controller.aberturaautomatica('Vila Olímpia', 'vaccines', 60, 15, 0, 2, 40)
controller.aberturaautomatica('Vila Olímpia', 'vaccines', 60, 6, 3, 4, 40)
controller.aberturaautomatica('Vila Olímpia', 'vaccines', 60, 1, 5, 6, 40)
controller.aberturaautomaticasobdemanda('Vila Olímpia', 'vaccines', 15, 0.3, 40, 1)
controller.aberturaautomaticasobdemanda('Vila Olímpia', 'vaccines', 10, 0.5, 40, 1)
# controller.aberturaautomaticasobdemanda('Vila Olímpia', 'vaccines', 7, 0, 40, 0)

controller.aberturaautomatica('Vila Olímpia', 'laboratories', 60, 15, 0, 2, 30)
controller.aberturaautomatica('Vila Olímpia', 'laboratories', 60, 6, 3, 4, 30)
controller.aberturaautomatica('Vila Olímpia', 'laboratories', 60, 1, 5, 6, 30)
controller.aberturaautomaticasobdemanda('Vila Olímpia', 'laboratories', 15, 0.3, 30, 1)
controller.aberturaautomaticasobdemanda('Vila Olímpia', 'laboratories', 10, 0.5, 30, 1)
# controller.aberturaautomaticasobdemanda('Vila Olímpia', 'laboratories', 7, 0, 30, 0)

controller.aberturaautomatica('São Bernardo do Campo', 'vaccines', 60, 15, 0, 2, 40)
controller.aberturaautomatica('São Bernardo do Campo', 'vaccines', 60, 6, 3, 4, 40)
controller.aberturaautomatica('São Bernardo do Campo', 'vaccines', 60, 1, 5, 6, 40)
controller.aberturaautomaticasobdemanda('São Bernardo do Campo', 'vaccines', 15, 0.3, 40, 1)
controller.aberturaautomaticasobdemanda('São Bernardo do Campo', 'vaccines', 10, 0.5, 40, 1)
# controller.aberturaautomaticasobdemanda('São Bernardo do Campo', 'vaccines', 7, 0, 40, 0)

controller.aberturaautomatica('São Bernardo do Campo', 'laboratories', 60, 15, 0, 2, 40)
controller.aberturaautomatica('São Bernardo do Campo', 'laboratories', 60, 6, 3, 4, 30)
controller.aberturaautomatica('São Bernardo do Campo', 'laboratories', 60, 1, 5, 6, 30)
controller.aberturaautomaticasobdemanda('São Bernardo do Campo', 'laboratories', 15, 0.3, 30, 1)
controller.aberturaautomaticasobdemanda('São Bernardo do Campo', 'laboratories', 10, 0.5, 30, 1)
# controller.aberturaautomaticasobdemanda('São Bernardo do Campo', 'laboratories', 7, 0, 30, 0)

controller.aberturaautomatica('Tatuapé', 'vaccines', 60, 15, 0, 2, 40)
controller.aberturaautomatica('Tatuapé', 'vaccines', 60, 6, 3, 4, 40)
controller.aberturaautomatica('Tatuapé', 'vaccines', 60, 1, 5, 6, 40)
controller.aberturaautomaticasobdemanda('Tatuapé', 'vaccines', 15, 0.3, 40, 1)
controller.aberturaautomaticasobdemanda('Tatuapé', 'vaccines', 10, 0.5, 40, 1)
# controller.aberturaautomaticasobdemanda('Tatuapé', 'vaccines', 7, 0, 40, 0)

controller.aberturaautomatica('Tatuapé', 'laboratories', 60, 15, 0, 2, 40)
controller.aberturaautomatica('Tatuapé', 'laboratories', 60, 6, 3, 4, 30)
controller.aberturaautomatica('Tatuapé', 'laboratories', 60, 1, 5, 6, 30)
controller.aberturaautomaticasobdemanda('Tatuapé', 'laboratories', 15, 0.3, 30, 1)
controller.aberturaautomaticasobdemanda('Tatuapé', 'laboratories', 10, 0.5, 30, 1)
# controller.aberturaautomaticasobdemanda('Tatuapé', 'laboratories', 7, 0, 30, 0)

controller.aberturaautomatica('Brasília', 'vaccines', 60, 15, 0, 2, 50)
controller.aberturaautomatica('Brasília', 'vaccines', 60, 6, 3, 4, 50)
controller.aberturaautomatica('Brasília', 'vaccines', 60, 1, 5, 6, 50)
controller.aberturaautomaticasobdemanda('Brasília', 'vaccines', 15, 0.3, 50, 1)
controller.aberturaautomaticasobdemanda('Brasília', 'vaccines', 10, 0.5, 50, 1)
# controller.aberturaautomaticasobdemanda('Brasília', 'vaccines', 7, 0, 50, 0)

controller.aberturaautomatica('Brasília', 'laboratories', 60, 15, 0, 2, 50)
controller.aberturaautomatica('Brasília', 'laboratories', 60, 6, 3, 4, 50)
controller.aberturaautomatica('Brasília', 'laboratories', 60, 1, 5, 6, 50)
controller.aberturaautomaticasobdemanda('Brasília', 'laboratories', 15, 0.3, 50, 1)
controller.aberturaautomaticasobdemanda('Brasília', 'laboratories', 10, 0.5, 50, 1)
# controller.aberturaautomaticasobdemanda('Brasília', 'laboratories', 7, 0, 50, 0)

controller.aberturaautomatica('Curitiba', 'vaccines', 60, 15, 0, 2, 50)
controller.aberturaautomatica('Curitiba', 'vaccines', 60, 6, 3, 4, 50)
controller.aberturaautomatica('Curitiba', 'vaccines', 60, 1, 5, 6, 50)
controller.aberturaautomaticasobdemanda('Curitiba', 'vaccines', 15, 0.3, 50, 1)
controller.aberturaautomaticasobdemanda('Curitiba', 'vaccines', 10, 0.5, 50, 1)
# controller.aberturaautomaticasobdemanda('Curitiba', 'vaccines', 7, 0, 50, 0)

controller.aberturaautomatica('Curitiba', 'laboratories', 60, 15, 0, 2, 50)
controller.aberturaautomatica('Curitiba', 'laboratories', 60, 6, 3, 4, 50)
controller.aberturaautomatica('Curitiba', 'laboratories', 60, 1, 5, 6, 50)
controller.aberturaautomaticasobdemanda('Curitiba', 'laboratories', 15, 0.3, 50, 1)
controller.aberturaautomaticasobdemanda('Curitiba', 'laboratories', 10, 0.5, 50, 1)
# controller.aberturaautomaticasobdemanda('Curitiba', 'laboratories', 7, 0, 50, 0)

controller.aberturaautomatica('Recife', 'vaccines', 60, 15, 0, 2, 40)
controller.aberturaautomatica('Recife', 'vaccines', 60, 6, 3, 4, 40)
controller.aberturaautomatica('Recife', 'vaccines', 60, 1, 5, 6, 40)
controller.aberturaautomaticasobdemanda('Recife', 'vaccines', 15, 0.3, 40, 1)
controller.aberturaautomaticasobdemanda('Recife', 'vaccines', 10, 0.5, 40, 1)
# controller.aberturaautomaticasobdemanda('Recife', 'vaccines', 7, 0, 50, 0)

controller.aberturaautomatica('Recife', 'laboratories', 60, 15, 0, 2, 40)
controller.aberturaautomatica('Recife', 'laboratories', 60, 6, 3, 4, 40)
controller.aberturaautomatica('Recife', 'laboratories', 60, 1, 5, 6, 40)
controller.aberturaautomaticasobdemanda('Recife', 'laboratories', 15, 0.3, 40, 1)
controller.aberturaautomaticasobdemanda('Recife', 'laboratories', 10, 0.5, 40, 1)
# controller.aberturaautomaticasobdemanda('Recife', 'laboratories', 7, 0, 50, 0)

controller.aberturaautomatica('Vitória', 'vaccines', 60, 15, 0, 2, 40)
controller.aberturaautomatica('Vitória', 'vaccines', 60, 6, 3, 4, 40)
controller.aberturaautomatica('Vitória', 'vaccines', 60, 1, 5, 6, 40)
controller.aberturaautomaticasobdemanda('Vitória', 'vaccines', 15, 0.3, 40, 1)
controller.aberturaautomaticasobdemanda('Vitória', 'vaccines', 10, 0.5, 40, 1)
# controller.aberturaautomaticasobdemanda('Vitória', 'vaccines', 7, 0, 50, 0)

controller.aberturaautomatica('Vitória', 'laboratories', 60, 15, 0, 2, 40)
controller.aberturaautomatica('Vitória', 'laboratories', 60, 6, 3, 4, 40)
controller.aberturaautomatica('Vitória', 'laboratories', 60, 1, 5, 6, 40)
controller.aberturaautomaticasobdemanda('Vitória', 'laboratories', 15, 0.3, 40, 1)
controller.aberturaautomaticasobdemanda('Vitória', 'laboratories', 10, 0.5, 40, 1)
# controller.aberturaautomaticasobdemanda('Vitória', 'laboratories', 7, 0, 50, 0)